[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "optionality"
version = "0.0.1"
requires-python = ">=3.12"
authors = [
    {name="juchengquan"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "yfinance",
    "tqdm",
    "moomoo-api",
    "pandas >= 2",
    "PyYAML >= 6",
    "pydantic[email]"
]

[project.optional-dependencies]
all = []

[dependency-groups]
dev = [
    "ruff"
]


[tool.ruff]
line-length = 120