"""monitor id to random hex

Revision ID: 2ebd4017d87f
Revises: 66da352e494e
Create Date: 2026-08-10 12:40:01.124013

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ebd4017d87f"
down_revision: str | Sequence[str] | None = "66da352e494e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), type_=sa.String(length=32), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.String(length=32), type_=sa.INTEGER(), existing_nullable=False)

    # ### end Alembic commands ###
