"""monitor last_alarm_at

Revision ID: 2f544aa4f35b
Revises: b4aff6eaa4c1
Create Date: 2026-08-10 19:01:04.065297

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f544aa4f35b"
down_revision: str | Sequence[str] | None = "b4aff6eaa4c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_alarm_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_column("last_alarm_at")

    # ### end Alembic commands ###
