"""monitor legs

Revision ID: 47e52961857e
Revises: f4f179222a09
Create Date: 2026-08-10 15:33:02.738150

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47e52961857e"
down_revision: str | Sequence[str] | None = "f4f179222a09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("legs", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_column("legs")

    # ### end Alembic commands ###
