"""monitors table

Revision ID: 66da352e494e
Revises: d81b9890d7a8
Create Date: 2026-08-10 11:33:51.918648

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66da352e494e"
down_revision: Union[str, Sequence[str], None] = "d81b9890d7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("strike_date", sa.String(length=10), nullable=False),
        sa.Column("option_type", sa.String(length=4), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("field", sa.String(length=50), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "field", name="uq_monitor_code_field"),
    )
    op.create_index(op.f("ix_monitors_code"), "monitors", ["code"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_monitors_code"), table_name="monitors")
    op.drop_table("monitors")
    # ### end Alembic commands ###
