"""positions table

Revision ID: 8c7c61cc8025
Revises: d62b29416294
Create Date: 2026-09-24 09:29:45.500998

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c7c61cc8025"
down_revision: str | Sequence[str] | None = "d62b29416294"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("strategy", sa.String(length=50), nullable=True),
        sa.Column("strike_date", sa.String(length=10), nullable=False),
        sa.Column("contracts", sa.Integer(), nullable=False),
        sa.Column("entry", sa.Float(), nullable=False),
        sa.Column("legs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_positions_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_name"))

    op.drop_table("positions")
    # ### end Alembic commands ###
