"""monitors span positions

Revision ID: 981090d4c5ac
Revises: d1068e6f8f25
Create Date: 2026-09-24 13:47:11.846704

"""

import json
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "981090d4c5ac"
down_revision: str | Sequence[str] | None = "d1068e6f8f25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitor_positions",
        sa.Column("monitor_id", sa.String(length=32), nullable=False),
        sa.Column("position_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("monitor_id", "position_id"),
    )
    # --- data, BEFORE position_id disappears ---
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "insert into monitor_positions (monitor_id, position_id)"
            " select id, position_id from monitors where position_id is not null"
        )
    )
    _split_legged_positions(conn)

    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_monitors_position_id"), type_="foreignkey")
        batch_op.drop_column("position_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_id", sa.VARCHAR(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f("fk_monitors_position_id"), "positions", ["position_id"], ["id"])

    op.drop_table("monitor_positions")
    # ### end Alembic commands ###


def _split_legged_positions(conn) -> None:
    """A wing watched on its own was entered on its own, so it is its own Position (ADR 0004).

    1016_IC is the case: the call spread opened 1 September, the put side 9 September. The
    surviving Position keeps the calls and takes the watching monitor's name so rule and
    holding line up; the puts become a new Position; the combined stop spans both.
    """
    winged = (
        conn.execute(
            sa.text(
                "select distinct mp.position_id from monitor_positions mp"
                " join monitors m on m.id = mp.monitor_id where m.scope in ('calls','puts')"
            )
        )
        .scalars()
        .all()
    )
    for position_id in winged:
        row = (
            conn.execute(
                sa.text("select name, strike_date, contracts, legs from positions where id = :i"),
                {"i": position_id},
            )
            .mappings()
            .one()
        )
        legs = json.loads(row["legs"]) if isinstance(row["legs"], str) else row["legs"]
        calls = [x for x in legs if x["option_type"] == "CALL"]
        puts = [x for x in legs if x["option_type"] == "PUT"]
        if not calls or not puts:
            continue

        wing_monitor = conn.execute(
            sa.text(
                "select m.id, m.code from monitors m"
                " join monitor_positions mp on mp.monitor_id = m.id"
                " where mp.position_id = :i and m.scope = 'calls'"
            ),
            {"i": position_id},
        ).first()

        conn.execute(
            sa.text("update positions set legs = :legs, name = :name where id = :i"),
            {
                "legs": json.dumps(calls),
                "name": wing_monitor[1] if wing_monitor else row["name"],
                "i": position_id,
            },
        )

        puts_id = uuid.uuid4().hex
        conn.execute(
            sa.text(
                "insert into positions (id, name, strategy, strike_date, contracts, entry, legs, created_at)"
                " values (:id, :name, null, :sd, :c, null, :legs, :ts)"
            ),
            {
                "id": puts_id,
                "name": f"{row['name']}_puts",
                "sd": row["strike_date"],
                "c": row["contracts"],
                "legs": json.dumps(puts),
                "ts": datetime.now(UTC).replace(tzinfo=None),
            },
        )

        if wing_monitor:
            conn.execute(sa.text("update monitors set scope = 'all' where id = :m"), {"m": wing_monitor[0]})

        # the rule covering every leg is the combined stop: span it across both Positions
        for monitor_id, monitor_legs in conn.execute(
            sa.text(
                "select m.id, m.legs from monitors m join monitor_positions mp on mp.monitor_id = m.id"
                " where mp.position_id = :i and m.scope = 'all' and m.legs is not null"
            ),
            {"i": position_id},
        ).all():
            parsed = json.loads(monitor_legs) if isinstance(monitor_legs, str) else monitor_legs
            if len(parsed) > len(calls):
                conn.execute(
                    sa.text("insert into monitor_positions (monitor_id, position_id) values (:m, :p)"),
                    {"m": monitor_id, "p": puts_id},
                )

        # a leg rule follows whichever Position now holds its contract
        put_strikes = [int(x["strike"]) for x in puts]
        for monitor_id, code in conn.execute(
            sa.text(
                "select m.id, m.code from monitors m join monitor_positions mp on mp.monitor_id = m.id"
                " where mp.position_id = :i and m.scope = 'leg'"
            ),
            {"i": position_id},
        ).all():
            if any(f"P{strike}000" in code for strike in put_strikes):
                conn.execute(
                    sa.text("update monitor_positions set position_id = :p where monitor_id = :m and position_id = :i"),
                    {"p": puts_id, "m": monitor_id, "i": position_id},
                )
