"""monitor compare mode

Revision ID: b4aff6eaa4c1
Revises: 47e52961857e
Create Date: 2026-08-10 18:46:29.847244

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4aff6eaa4c1"
down_revision: str | Sequence[str] | None = "47e52961857e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("compare", sa.String(length=6), server_default="abs", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_column("compare")

    # ### end Alembic commands ###
