"""monitor position link and nullable entry

Revision ID: d1068e6f8f25
Revises: 8c7c61cc8025
Create Date: 2026-09-24 10:20:02.130396

"""

import json
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op
from optionality.apis.aux import build_spx_code

# revision identifiers, used by Alembic.
revision: str = "d1068e6f8f25"
down_revision: str | Sequence[str] | None = "8c7c61cc8025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("position_id", sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column("scope", sa.String(length=10), nullable=True))
        batch_op.create_foreign_key("fk_monitors_position_id", "positions", ["position_id"], ["id"])

    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.alter_column("entry", existing_type=sa.FLOAT(), nullable=True)

    # ### end Alembic commands ###

    # --- data: combos become Positions; wing watchers become scoped Monitors (ADR 0003) ---
    conn = op.get_bind()
    rows = (
        conn.execute(sa.text("select id, code, strike_date, legs from monitors where legs is not null"))
        .mappings()
        .all()
    )
    combos = [dict(r, legs=json.loads(r["legs"]) if isinstance(r["legs"], str) else r["legs"]) for r in rows]

    def sided(legs):
        # the live convention, verified across every stored combo: '-' on sold, '+' on bought
        return [
            {
                "side": "sold" if leg["sign"] < 0 else "bought",
                "option_type": leg["option_type"],
                "strike": float(leg["strike"]),
            }
            for leg in legs
        ]

    def key(legs, option_type=None):
        return sorted(
            (leg["option_type"], float(leg["strike"]), leg["side"])
            for leg in legs
            if option_type is None or leg["option_type"] == option_type
        )

    sided_by_id = {c["id"]: sided(c["legs"]) for c in combos}

    # a combo whose legs are exactly the calls (or puts) of a larger combo at the same expiry
    # is not a separate holding — it is how that wing is watched
    wing_of = {}
    for a in combos:
        for b in combos:
            if a["id"] == b["id"] or a["strike_date"] != b["strike_date"]:
                continue
            if len(sided_by_id[a["id"]]) >= len(sided_by_id[b["id"]]):
                continue
            for option_type, scope in (("CALL", "calls"), ("PUT", "puts")):
                if key(sided_by_id[a["id"]]) and key(sided_by_id[a["id"]]) == key(sided_by_id[b["id"]], option_type):
                    wing_of[a["id"]] = (b["id"], scope)
                    break

    position_of_combo = {}
    for combo in combos:
        if combo["id"] in wing_of:
            continue
        pid = uuid.uuid4().hex
        conn.execute(
            sa.text(
                "insert into positions (id, name, strategy, strike_date, contracts, entry, legs, created_at)"
                " values (:id, :name, null, :strike_date, 1, null, :legs, :created_at)"
            ),
            {
                "id": pid,
                "name": combo["code"],
                "strike_date": combo["strike_date"],
                "legs": json.dumps(sided_by_id[combo["id"]]),
                "created_at": datetime.now(UTC).replace(tzinfo=None),
            },
        )
        position_of_combo[combo["id"]] = pid
        conn.execute(
            sa.text("update monitors set position_id = :pid, scope = 'all' where id = :mid"),
            {"pid": pid, "mid": combo["id"]},
        )

    for monitor_id, (parent_id, scope) in wing_of.items():
        conn.execute(
            sa.text("update monitors set position_id = :pid, scope = :scope where id = :mid"),
            {"pid": position_of_combo[parent_id], "scope": scope, "mid": monitor_id},
        )

    # single-contract monitors attach to the Position holding that exact leg, but only when
    # exactly one does; an ambiguous match is left unlinked rather than guessed
    leg_owner = {}
    for combo_id, pid in position_of_combo.items():
        expiry = next(c["strike_date"] for c in combos if c["id"] == combo_id)
        for leg in sided_by_id[combo_id]:
            leg_owner.setdefault(build_spx_code(expiry, leg["option_type"], leg["strike"]), []).append(pid)

    singles = conn.execute(sa.text("select id, code from monitors where legs is null")).mappings().all()
    for single in singles:
        owners = leg_owner.get(single["code"], [])
        if len(owners) == 1:
            conn.execute(
                sa.text("update monitors set position_id = :pid, scope = 'leg' where id = :mid"),
                {"pid": owners[0], "mid": single["id"]},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.alter_column("entry", existing_type=sa.FLOAT(), nullable=False)

    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_constraint("fk_monitors_position_id", type_="foreignkey")
        batch_op.drop_column("scope")
        batch_op.drop_column("position_id")

    # ### end Alembic commands ###
