"""monitor disabled reason

Revision ID: d62b29416294
Revises: 2f544aa4f35b
Create Date: 2026-09-07 09:11:48.435830

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d62b29416294"
down_revision: str | Sequence[str] | None = "2f544aa4f35b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("disabled_reason", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_column("disabled_reason")

    # ### end Alembic commands ###
