"""initial schema

Revision ID: ea9f9857e730
Revises:
Create Date: 2026-08-10 13:23:40.737201

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea9f9857e730"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("configs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_configs_name"), ["name"], unique=True)

    op.create_table(
        "monitors",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("strike_date", sa.String(length=10), nullable=False),
        sa.Column("option_type", sa.String(length=4), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("field", sa.String(length=50), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("last_value", sa.Float(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "field", name="uq_monitor_code_field"),
    )
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_monitors_code"), ["code"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("config_name", sa.String(length=100), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("notify", sa.Boolean(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cron_expr", sa.String(length=100), nullable=False),
        sa.Column("tz", sa.String(length=50), nullable=False),
        sa.Column("task_type", sa.String(length=20), nullable=False),
        sa.Column("config_name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reports",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    op.drop_table("schedules")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_created_at"))

    op.drop_table("runs")
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitors_code"))

    op.drop_table("monitors")
    with op.batch_alter_table("configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configs_name"))

    op.drop_table("configs")
    # ### end Alembic commands ###
