"""monitor direction

Revision ID: f4f179222a09
Revises: ea9f9857e730
Create Date: 2026-08-10 14:52:49.994594

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4f179222a09"
down_revision: str | Sequence[str] | None = "ea9f9857e730"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("direction", sa.String(length=5), server_default="above", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("monitors", schema=None) as batch_op:
        batch_op.drop_column("direction")

    # ### end Alembic commands ###
